---
- hosts: rhel
  become: true
  vars:
    bigfix_client_service_name: besclient
  tasks:
    - name: Load OS specific vars
      include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}-{{ ansible_architecture }}.yml"

    - name: Failing due to undetermined OS
      fail:
        msg: OS could not be determined.
      when: bigfix_client_file_sum is not defined

    - include: uninstall.yml
    

