---

- name: Stop the service
  service:
    name: "{{ bigfix_client_service_name }}"
    state: stopped

- name: Check bigfix version
  raw: rpm -qa | grep -i besa > /tmp/agentversion.txt

- name: Get bigfix version
  shell: cat /tmp/agentversion.txt
  register: bigfix

- debug: var=bigfix.stdout_lines

- name: Uninstall BigFix Client
  yum:
    name: "{{ bigfix.stdout }}"
    state: absent
